### ISSUE TITLE
requesting support with 1.4 port of calamity mod

### ISSUE THREAD

**Issue by Icyunspeakable** [VVV101/AlchemistNPCLite#23]
currently the operator doesn't sell the lootbags or materials from calamity mod upon defeating any bosses from calamity mod. I understand that calamity mod 2.0.001 came out a few days ago and thus it makes sense that the compatibility is lacking. I hope that I don't add more to your TO-DO list as you most likely have your hands full with the full version of AlchemistNPC, I appreciate the work that you guys have done and I love this mod, I can't wait to see where it will go in the future!

**Comment by martinleonardo** [comment]
Most Calamity items have been added back with #24
